version: '2'

services:
    alpinepsql:
        restart: always
        image: 'postgres-imagen'
        build: ./postgres/.
        container_name: 'psqlalpine-prn335'
        environment: 
        - POSTGRES_USER=mortal2017
        - POSTGRES_PASSWORD=prn335
        - POSTGRES_DB=posts
        ports:
        - '5432:5432'
        volumes:
        - pgdata:/var/lib/postgresql/data
    payaracont: 
        image: 'payara-imagen'
        build: ./payara/.   
        container_name: 'payara-prn335'
        depends_on:
        - 'alpinepsql'
        ports:
        - "8080:8080"
        - "4848:4848"
        entrypoint:
        - "bin/asadmin"
        - "start-domain"
        - "-v"
volumes:
   pgdata:

 

